spring:
  application:
    name: game24
  web:
    error:
      include-stacktrace: never

server:
  address: 0.0.0.0

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: "*"

game24:
    maximum-game-generation-attempts: 1_000